modbus_server: # require service restart
  accept: 0.0.0.0
  port: 502
capture: # may be changed without restart
  folder: ./capture
  frames: 50
camera:
  # valid values: "ANY", "DSHOW", "QT", "MSMF", "OPENNI", "FFMPEG", "OPENCV_MJPEG", "V4L", "V4L2", "INTEL_MFX"
  format: DSHOW
logging:
  level: INFO